version: '3.1'
services:
  cassandra-1:
    hostname: cassandra-1
    environment:
      HEAP_NEWSIZE: "128M"
      MAX_HEAP_SIZE: "1024M"
    image: cassandra:3.11
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "127.0.0.1:9042:9042"
